spring:
  application:
    name: Backend

  datasource:
    # Replace 'your_database_name' with your actual MySQL database name (e.g., mamacare-database-real)
    url: jdbc:mysql://34.60.140.34:3306/mamacare-database-real?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ${GCP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000

cors:
  allowed-origins: 'http://localhost:19006'
